[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "darmuh"
name = "OpenLib_DawnlibExperimental_Compatibility"
description = "DawnlibExperimental Compatibility version of OpenLib"
websiteUrl = "https://github.com/darmuh/OpenLib" # TODO: Add a link to your mod repository here (optional)
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2305"

[build]
icon = "/_Release Files/icon.png"
readme = "/_Release Files/README.md"
outdir = "/artifacts/thunderstore/"

[[build.copy]]
source = "/artifacts/bin/OpenLib/release/OpenLib.dll"
target = "plugins/"

[[build.copy]]
source = "/_Release Files/CHANGELOG.md"
target = "/"

[[build.copy]]
source = "/_Release Files/LICENSE.MD"
target = "/"

[[build.copy]]
source = "_Release Files/openlib.bundle"
target = "plugins/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "lethal-company" ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/lethal-company/category/
repo = [ "libraries" ]
